users.endpoint:
  uri: '/v1/users'
  dispatch: 'Roducks\Modules\Users\Api\Users'
  services:
    - user
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  jwt: true
users.me:
  uri: '/v1/me'
  dispatch: 'Roducks\Modules\Users\Api\Users::me'
  services:
    - user
  methods:
    - GET
  jwt: true
users.auth:
  uri: '/v1/auth'
  dispatch: 'Roducks\Modules\Users\Api\Auth::federate'
  services:
    - user
  methods:
    - POST